### ISSUE TITLE
タスク完了機能の追加

### ISSUE THREAD

**Issue by YumaNaganoSC** [YumaNaganoSC/itce202112-laravel#6]
## 目的
* タスクの完了状態を追加することで、タスクが完了しても記録として残せるようにするため

## 完了条件
* [x] 完了タスクの一覧があること
* [x] タスク完了ボタンがあること
* [x] タスク完了を取り消すボタンがあること

## Q
* [x] 完了タスクの一覧について、以下とするのは問題ないか
  * 絞り込み機能のデフォルトを「未着手」「着手中」にして、「完了」のタスクはデフォルトで表示しないようにする
* [x] タスク完了を取り消すボタンについて、「未着手」「着手中」におけるタスク完了ボタンと同じ場所の配置で良いか

**Comment by Yuma-Nagano** [comment]
> 完了タスクの一覧について、以下とするのは問題ないか  
> 絞り込み機能のデフォルトを「未着手」「着手中」にして、「完了」のタスクはデフォルトで表示しないようにする

上記について、https://github.com/YumaNaganoSC/itce202112-laravel/issues/4 完了後にhttps://github.com/YumaNaganoSC/itce202112-laravel/issues/11 で着手する。
